### ISSUE TITLE
Not drawing progress with Android sdk version 29

### ISSUE THREAD

**Issue by rolud** [dinuscxj/CircleProgressBar#25]
I update sdk version in app gradle
```
compileSdkVersion 29
    buildToolsVersion '29.0.3'
    defaultConfig {
        ...
        minSdkVersion 21
        targetSdkVersion 29
        ....
    }
```
Previously was 
```
compileSdkVersion 28
    buildToolsVersion '28.0.3'
    defaultConfig {
        ...
        minSdkVersion 21
        targetSdkVersion 28
        ....
    }
```

Now `CircleProgressBar` can't draw progress bar updates. I logged this:
```
 handleWindowVisibility: no activity for token android.os.BinderProxy@bc6037b
 Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
 Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
 Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
 Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
 mapper 3.x is not supported
 handleWindowVisibility: no activity for token android.os.BinderProxy@beccbe1
 Accessing hidden field Landroid/widget/ProgressBar;->mOnlyIndeterminate:Z (greylist, reflection, allowed)
 Accessing hidden field Landroid/widget/ProgressBar;->mIndeterminate:Z (greylist-max-p, reflection, denied)
 java.lang.NoSuchFieldException: No field mIndeterminate in class Landroid/widget/ProgressBar; (declaration of 'android.widget.ProgressBar' appears in /system/framework/framework.jar!classes3.dex)
     at java.lang.Class.getDeclaredField(Native Method)
     at com.dinuscxj.progressbar.CircleProgressBar.adjustIndeterminate(CircleProgressBar.java:220)
     at com.dinuscxj.progressbar.CircleProgressBar.<init>(CircleProgressBar.java:111)
     at java.lang.reflect.Constructor.newInstance0(Native Method)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
     at android.view.LayoutInflater.createView(LayoutInflater.java:854)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
     at java.lang.reflect.Constructor.newInstance0(Native Method)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
     at android.view.LayoutInflater.createView(LayoutInflater.java:854)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
     at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1816)
     at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
     at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:262)
     at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
     at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
     at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
     at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1009)
     at android.view.View.measure(View.java:26415)
     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3605)
     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2348)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2640)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
     at android.view.Choreographer.doCallbacks(Choreographer.java:794)
     at android.view.Choreographer.doFrame(Choreographer.java:729)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
     at android.os.Handler.handleCallback(Handler.java:883)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:237)
     at android.app.ActivityThread.main(ActivityThread.java:7814)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```
I am using version 1.1.1.
```
implemetation {
    implementation 'com.dinuscxj:circleprogressbar:1.1.1'
}
```

**Comment by rolud** [comment]
Problem is solved in version 1.3.6
